package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Book;
import org.apache.ibatis.annotations.*;
import org.mybatis.cdi.Mapper;


import java.util.List;
@Mapper
public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    List<Book> findAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    void insert(Book book);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    void update(Book book);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    void delete(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    Book findById(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    List<Book> findByAuthorId(Integer authorId);

}

