package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Contact;
import org.apache.ibatis.annotations.*;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface ContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    List<Contact> findAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    Contact findById(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    void insert(Contact contact);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    void update(Contact contact);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    void deleteById(int id);
}
