package lt.vu.mybatis.model;

public class Contact {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    private String contactDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    private String contactInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    private Integer authorId;

}
